In [2]:
import yfinance as yf

# Define the ticker symbol
ticker_symbol = "AAPL"

# Create a ticker object
ticker = yf.Ticker(ticker_symbol)

# Download historical data
#historical_data = ticker.history(start="1990-01-01", end="2022-12-31", interval='1d')
historical_data = ticker.history(period="10d", interval='1h')

In [3]:
len(historical_data)

68

available timeframes: 1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo >>>
1m data is only retrievable for the last 7 days, and anything intraday (interval <1d) only for the last 60 days.

In [4]:
historical_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-06-17 09:30:00-04:00,197.250000,197.929993,196.255005,197.580002,7902396,0.0,0.0
2025-06-17 10:30:00-04:00,197.582993,197.789993,197.324997,197.580002,3367583,0.0,0.0
2025-06-17 11:30:00-04:00,197.589996,198.388901,197.460007,197.615005,3514424,0.0,0.0
2025-06-17 12:30:00-04:00,197.610001,197.845703,196.464996,196.520004,4473741,0.0,0.0
2025-06-17 13:30:00-04:00,196.509995,196.820007,195.210007,195.460007,4011630,0.0,0.0
...,...,...,...,...,...,...,...
2025-07-01 09:30:00-04:00,206.664993,209.830002,206.140106,209.540100,26727091,0.0,0.0
2025-07-01 10:30:00-04:00,209.550095,210.186493,207.470001,207.949997,15475523,0.0,0.0
2025-07-01 11:30:00-04:00,207.960007,208.184998,206.789993,207.875000,7412772,0.0,0.0
2025-07-01 12:30:00-04:00,207.869995,208.529999,207.100006,208.110306,6007346,0.0,0.0
2025-07-01 13:30:00-04:00,208.119995,208.369995,207.610001,208.289993,2624228,0.0,0.0

In [5]:
historical_data = ticker.history(interval="90m", start="2025-06-25", end="2025-07-01")

In [6]:
historical_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-06-25 09:30:00-04:00,201.419998,203.660004,201.199997,202.455002,14032443,0.0,0.0
2025-06-25 11:00:00-04:00,202.440002,202.550003,201.399994,201.869995,6347810,0.0,0.0
2025-06-25 12:30:00-04:00,201.880005,202.179703,200.620102,200.999893,4889030,0.0,0.0
2025-06-25 14:00:00-04:00,201.000000,201.500000,200.855804,201.159805,4174557,0.0,0.0
2025-06-25 15:30:00-04:00,201.139999,201.619995,200.884995,201.600006,4058748,0.0,0.0
2025-06-26 09:30:00-04:00,202.350006,202.615005,199.649994,200.279907,14994341,0.0,0.0
2025-06-26 11:00:00-04:00,200.300003,200.789993,199.460007,200.122803,7671905,0.0,0.0
2025-06-26 12:30:00-04:00,200.137802,200.710007,199.634995,200.630005,6647989,0.0,0.0
2025-06-26 14:00:00-04:00,200.639999,201.360001,200.429993,201.175003,6919953,0.0,0.0
2025-06-26 15:30:00-04:00,201.175201,201.559998,200.789993,200.940002,5945620,0.0,0.0
2025-06-27 09:30:00-04:00,201.895004,203.220001,200.854996,201.198700,15283281,0.0,0.0
2025-06-27 11:00:00-04:00,201.210007,202.050003,200.955002,201.990005,6321915,0.0,0.0
2025-06-27 12:30:00-04:00,201.990005,202.699997,200.929993,201.373596,7493250,0.0,0.0
2025-06-27 14:00:00-04:00,201.384796,201.656799,200.789993,201.125000,7492599,0.0,0.0
2025-06-27 15:30:00-04:00,201.130005,201.270004,200.220001,201.100006,6326536,0.0,0.0
2025-06-30 09:30:00-04:00,202.009995,202.190002,199.590103,199.970001,14509917,0.0,0.0
2025-06-30 11:00:00-04:00,199.970001,200.419998,199.630005,200.324997,7491005,0.0,0.0
2025-06-30 12:30:00-04:00,200.309998,200.479996,199.845001,200.270004,5951262,0.0,0.0
2025-06-30 14:00:00-04:00,200.274994,207.089996,199.260696,206.585602,28860636,0.0,0.0
2025-06-30 15:30:00-04:00,206.550003,207.389999,205.050003,205.119995,13956446,0.0,0.0

In [7]:
historical_data = ticker.history(period="1mo", start="2025-01-25", end="2025-07-01")

In [8]:
historical_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-01-27 00:00:00-05:00,223.480912,231.591337,223.440999,229.306854,94863400,0.0,0.0
2025-01-28 00:00:00-05:00,230.294474,239.611994,230.254561,237.686630,75707600,0.0,0.0
2025-01-29 00:00:00-05:00,233.556586,239.282778,233.446850,238.783981,45486100,0.0,0.0
2025-01-30 00:00:00-05:00,238.095637,240.210530,236.639159,237.018234,55658300,0.0,0.0
2025-01-31 00:00:00-05:00,246.595158,246.595158,232.878246,235.432083,101075100,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-24 00:00:00-04:00,202.589996,203.440002,200.199997,200.300003,54064000,0.0,0.0
2025-06-25 00:00:00-04:00,201.449997,203.669998,200.619995,201.559998,39525700,0.0,0.0
2025-06-26 00:00:00-04:00,201.429993,202.639999,199.460007,201.000000,50799100,0.0,0.0
2025-06-27 00:00:00-04:00,201.889999,203.220001,200.000000,201.080002,73188600,0.0,0.0
2025-06-30 00:00:00-04:00,202.009995,207.389999,199.259995,205.169998,91612700,0.0,0.0

In [9]:
#data = yf.download("AAPL", start="2022-05-01", end="2022-05-03",  interval = "1m")
ticker.history(interval="1d", start="1990-01-01", end="2022-12-31")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1990-01-02 00:00:00-05:00,0.247458,0.263254,0.245704,0.261499,183198400,0.0,0.0
1990-01-03 00:00:00-05:00,0.266764,0.266764,0.263254,0.263254,207995200,0.0,0.0
1990-01-04 00:00:00-05:00,0.268519,0.272029,0.261499,0.264132,221513600,0.0,0.0
1990-01-05 00:00:00-05:00,0.265009,0.268519,0.259744,0.265009,123312000,0.0,0.0
1990-01-08 00:00:00-05:00,0.263253,0.266764,0.259744,0.266764,101572800,0.0,0.0
...,...,...,...,...,...,...,...
2022-12-23 00:00:00-05:00,129.245801,130.726619,127.982170,130.173782,63814900,0.0,0.0
2022-12-27 00:00:00-05:00,129.699945,129.729560,127.073957,128.367203,69007800,0.0,0.0
2022-12-28 00:00:00-05:00,128.011777,129.354385,124.260376,124.428200,85438400,0.0,0.0
2022-12-29 00:00:00-05:00,126.353297,128.811453,126.096627,127.952583,75703700,0.0,0.0
2022-12-30 00:00:00-05:00,126.767927,128.288227,125.800455,128.268478,77034200,0.0,0.0